// <auto-generated />
using System;
using C229_G2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace C229_G2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190411194556_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("C229_G2.Models.Club", b =>
                {
                    b.Property<int>("ClubID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.HasKey("ClubID");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("C229_G2.Models.Match", b =>
                {
                    b.Property<int>("MatchID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AwayCorners");

                    b.Property<int>("AwayFouls");

                    b.Property<int>("AwayGoals");

                    b.Property<int>("AwayShotsOnTarget");

                    b.Property<int?>("AwayTeamTeamID");

                    b.Property<DateTime>("Date");

                    b.Property<int>("HomeCorners");

                    b.Property<int>("HomeFouls");

                    b.Property<int>("HomeGoals");

                    b.Property<int>("HomeShotsOnTarget");

                    b.Property<int?>("HomeTeamTeamID");

                    b.Property<string>("Location");

                    b.Property<string>("Referee");

                    b.HasKey("MatchID");

                    b.HasIndex("AwayTeamTeamID");

                    b.HasIndex("HomeTeamTeamID");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("C229_G2.Models.MatchPlayer", b =>
                {
                    b.Property<int>("MatchPlayerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Goals");

                    b.Property<int?>("MatchID");

                    b.Property<int>("RedCards");

                    b.Property<int?>("TeamPlayerID");

                    b.Property<int>("YellowCards");

                    b.HasKey("MatchPlayerID");

                    b.HasIndex("MatchID");

                    b.HasIndex("TeamPlayerID");

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("C229_G2.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<int?>("ClubID");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<decimal>("Height");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<decimal>("Weight");

                    b.HasKey("PlayerID");

                    b.HasIndex("ClubID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("C229_G2.Models.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("PlayerID");

                    b.Property<int>("Score");

                    b.HasKey("SkillID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("C229_G2.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClubID");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("TeamID");

                    b.HasIndex("ClubID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("C229_G2.Models.TeamPlayer", b =>
                {
                    b.Property<int>("TeamPlayerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PlayerID");

                    b.Property<string>("Position")
                        .IsRequired();

                    b.Property<int>("TeamID");

                    b.HasKey("TeamPlayerID");

                    b.HasIndex("PlayerID");

                    b.HasIndex("TeamID");

                    b.ToTable("TeamPlayers");
                });

            modelBuilder.Entity("C229_G2.Models.Match", b =>
                {
                    b.HasOne("C229_G2.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamTeamID");

                    b.HasOne("C229_G2.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamTeamID");
                });

            modelBuilder.Entity("C229_G2.Models.MatchPlayer", b =>
                {
                    b.HasOne("C229_G2.Models.Match", "Match")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("MatchID");

                    b.HasOne("C229_G2.Models.TeamPlayer", "TeamPlayer")
                        .WithMany()
                        .HasForeignKey("TeamPlayerID");
                });

            modelBuilder.Entity("C229_G2.Models.Player", b =>
                {
                    b.HasOne("C229_G2.Models.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubID");
                });

            modelBuilder.Entity("C229_G2.Models.Skill", b =>
                {
                    b.HasOne("C229_G2.Models.Player", "Player")
                        .WithMany("Skills")
                        .HasForeignKey("PlayerID");
                });

            modelBuilder.Entity("C229_G2.Models.Team", b =>
                {
                    b.HasOne("C229_G2.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubID");
                });

            modelBuilder.Entity("C229_G2.Models.TeamPlayer", b =>
                {
                    b.HasOne("C229_G2.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerID");

                    b.HasOne("C229_G2.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
